# Generated by Django 4.1.7 on 2023-02-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("image", models.ImageField(upload_to="card_imgs")),
            ],
        ),
        migrations.CreateModel(
            name="SubEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=50)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ParticipantsSubEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.participants",
                    ),
                ),
                (
                    "subevent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.subevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.eventmanager",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSubEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "subevent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.subevent",
                    ),
                ),
            ],
        ),
    ]
